sonar.projectKey=ms-citizen
sonar.projectName=ms-citizen
sonar.projectVersion=0.1.0-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Excluir boilerplate de cobertura
sonar.coverage.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.java
